require('dotenv').config()
const app = require('./app')

const PORT = process.env.PORT || 3000

app.listen(PORT, () => {
  console.log(`🚀 Local backend server running on http://localhost:${PORT}`)
  console.log(`📋 Available routes:`)
  console.log(`   - POST   /auth/register`)
  console.log(`   - POST   /auth/login`)
  console.log(`   - GET    /auth/profile`)
  console.log(`   - POST   /storefronts`)
  console.log(`   - GET    /storefronts`)
  console.log(`   - GET    /storefronts/:storeId`)
  console.log(`   - GET    /storefronts/my`)
  console.log(`   - POST   /listings`)
  console.log(`   - GET    /listings?storeId=...`)
  console.log(`   - GET    /listings/:id`)
  console.log(`   - PUT    /listings/:id`)
  console.log(`   - DELETE /listings/:id`)
  console.log(`   - GET    /cart/items`)
  console.log(`   - POST   /cart/items`)
  console.log(`   - PATCH  /cart/items/:itemId`)
  console.log(`   - DELETE /cart/items/:itemId`)
  console.log(`   - DELETE /cart/items`)
  console.log(`   - POST   /orders`)
  console.log(`   - GET    /orders`)
  console.log(`   - GET    /orders/:orderId`)
  console.log(`   - POST   /reviews`)
  console.log(`   - GET    /reviews/product/:productId`)
  console.log(`   - GET    /reviews/:reviewId`)
  console.log(`   - POST   /subscriptions/subscribe`)
  console.log(`   - POST   /subscriptions/unsubscribe`)
  console.log(`   - GET    /subscriptions/:storeId`)
  console.log(`   - GET    /chats`)
  console.log(`   - POST   /chats`)
  console.log(`   - GET    /chats/:chatId`)
  console.log(`   - GET    /chats/:chatId/messages`)
  console.log(`   - POST   /chats/:chatId/messages`)
  console.log(`   - PUT    /chats/:chatId/messages/:messageId/read`)
  console.log(`   - PUT    /chats/:chatId/read-all`)
  console.log(`   - DELETE /chats/:chatId`)
  console.log(`   - GET    /chats/store/:storeId`)
})

